name: Generate 3D Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every midnight
  workflow_dispatch:  # Allows you to manually run the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: vishalbodkhe531
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg
      - name: Commit files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Generated 3D snake contribution grid"
          git push
